apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-info
  namespace: employee

spec:
  replicas: 2

  selector:
    matchLabels:
      app: emp-info

  template:
    metadata:
      labels:
        app: emp-info

    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
          

      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for MySQL..."
          sleep 10
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi" 


        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          capabilities:
             drop:
               - ALL

      containers:
      - name: emp-info
        image: ravikumardahat/employee-connect:latest

        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          capabilities:
             drop:
               - All 

        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
               configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST
        - name: MYSQL_DATABASE            
          valueFrom:
             configMapKeyRef:
                name: mysql-config
                key:  MYSQL_DATABASE 
        ports:
        - containerPort: 5000

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
