apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: mysql
spec:
    serviceName: mysql
    replicas: 1
    selector:
        matchLabels:
             app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
             securityContext:
                seccompProfile:
                    type: RuntimeDefault
             containers:
                 - name: mysql
                   image: mysql:8.0
                   securityContext:
                       allowPrivilegeEscalation: false
                       runAsNonRoot: true
                       runAsUser: 1000
                       runAsGroup: 1000
                       readOnlyRootFilesystem: true
                       capabilities:
                          drop:
                            - ALL
                   env:
                       - name: MYSQL_ROOT_PASSWORD
                         value: root123
                       - name: MYSQL_DATABASE
                         value: employee_db
                   ports:
                      - containerPort: 3306

                   volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql

    volumeClaimTemplates:
     - metadata:
         name: mysql-data
       spec:
         accessModes:
            - ReadWriteOnce
         storageClassName: local-path
         resources:
             requests:
                storage: 1Gi
