name: Code Scan

on: 
   workflow_call:
   workflow_dispatch:

jobs:
    code-scan:
       runs-on: ubuntu-latest

       steps:
           - uses: actions/checkout@v4

           - uses: actions/setup-python@v5
             with:
                  python-version: '3.11'
           - name: Install Tools
             run: |
                    pip install flask8 bandit pip-audit
                    pip install -r requirments.txt
                    
           - name: Flask8 scan
             run: flask8 .
           - name: Run Depndency scan

             run: pip-audit   
           - name: Bandit scan
             run: bandit -r .       