name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  code-scan:
    uses: ./.github/workflows/code-scan.yaml

  docker-build:
    needs: code-scan
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit

  image-scan:
    needs: docker-build
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit