name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  code-scan:
    uses: ./.github/workflows/code-scan.yaml

  secret-scan:
    
    uses: ./.github/workflows/secret-scan.yml
  dockerfile-scan:
     uses: ./.github/workflows/docker-scan.yaml
  docker-build:

    needs: [code-scan ,secret-scan, dockerfile-scan]
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit


    

  image-scan:
    needs: docker-build
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
  k8s-scan:
    needs: image-scan
    uses: ./.github/workflows/k8s-scan.yaml  