name: Image Scan

on: 
   workflow_call:

jobs:
    image-scan:
       runs-on: ubuntu-latest

       steps:
           - uses: actions/checkout@v4

           - name: TrivyScan
             uses: aquasecurity/trivy-action@master
             with:
               image-ref: employee-portal:${{ github.sha }}
               severity: HIGH,CRITICAL
               exit-code: 1
            