name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:

  code-scan:
    uses: ./.github/workflows/code-scanner.yml

  image-scan:
    needs: code-scan
    uses: ./.github/workflows/image-scanner.yml

  docker-build:
    needs: image-scan
    uses: ./.github/workflows/docker-build.yml
